-- Exported by JKG Dialogue Creator

DLG.Name = "imp_faq_droid_dlg"
DLG.RootNode = "E1"
DLG.Nodes = {
	E1 = {
		Type = 1,
		SubNode = "T2",
		HasCondition = false,
	},
	T2 = {
		Type = 2,
		SubNode = "O3",
		Text = "Greetings $name$, can I assist you?",
		Duration = 5500,
		HasCondition = false,
		HasResolver = true,
		ResolveFunc = function(owner, ply, var, data)
			if var == "name" then
			    return sys.StripColorcodes(ply:GetName())
			end
			
			return ""
		end,
	},
	O3 = {
		Type = 3,
		SubNode = "S106",
		NextNode = "O4",
		Text = "How do I purchase a weapon?",
		HasCondition = false,
		HasResolver = false,
	},
	S106 = {
		Type = 6,
		NextNode = "T10",
		ScriptFunc = function(owner, ply, data)
			--[[-----------------------------------------------
				Dialogue Script
			
				Available Variables:
				owner - Entity that runs this conversation
				ply	  - Player the owner is talking to
				data - Local storage table
			--]]-----------------------------------------------
			
				ply:SetAnimBoth("BOTH_STAND1_TALK1")
				ply:SetAnimHoldTime(3, 1500)
		end,
		HasCondition = false,
	},
	T10 = {
		Type = 2,
		SubNode = "T11",
		Text = "Weapons are purchased at our Imperial arms reserve.",
		Duration = 5200,
		HasCondition = false,
		HasResolver = false,
	},
	T11 = {
		Type = 2,
		SubNode = "T12",
		Text = "Speak to the Officer behind the desk to stock up.",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	T12 = {
		Type = 2,
		SubNode = "L102",
		Text = "A grayed out gun in the holoscreen means \nyou do not have enough credits to purchase it.",
		Duration = 5500,
		HasCondition = false,
		HasResolver = false,
	},
	L102 = {
		Type = 4,
		Target = "O51",
	},
	O4 = {
		Type = 3,
		SubNode = "S107",
		NextNode = "O17",
		Text = "What's my objective?",
		HasCondition = false,
		HasResolver = false,
	},
	S107 = {
		Type = 6,
		NextNode = "T5",
		ScriptFunc = function(owner, ply, data)
			
				ply:SetAnimBoth("BOTH_STAND1_TALK2")
				ply:SetAnimHoldTime(1500, 1)
		end,
		HasCondition = false,
	},
	T5 = {
		Type = 2,
		SubNode = "T91",
		Text = "It's not unusual our presence here be unwanted.\nLocal mercenaries and rebel groups can stir up a fuss.",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	T91 = {
		Type = 2,
		SubNode = "L101",
		NextNode = "S108",
		Text = "Neutralize the threat.",
		Duration = 4500,
		HasCondition = false,
		HasResolver = false,
	},
	L101 = {
		Type = 4,
		Target = "O51",
	},
	S108 = {
		Type = 6,
		ScriptFunc = function(owner, ply, data)
			
				owner:SetAnimBoth("BOTH_TALK2")
				owner:SetAnimHoldTime(3, 5000)
		end,
		HasCondition = false,
	},
	O17 = {
		Type = 3,
		SubNode = "T18",
		NextNode = "O38",
		Text = "Anything I should know about before I purchase weapons?",
		HasCondition = false,
		HasResolver = false,
	},
	T18 = {
		Type = 2,
		SubNode = "T19",
		Text = "Absolutely!",
		Duration = 1000,
		HasCondition = false,
		HasResolver = false,
	},
	T19 = {
		Type = 2,
		SubNode = "O20",
		Text = "Would you like to discuss which weapon you should buy first?",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	O20 = {
		Type = 3,
		SubNode = "T22",
		NextNode = "O21",
		Text = "No, I'm okay. What else should I know?",
		HasCondition = false,
		HasResolver = false,
	},
	T22 = {
		Type = 2,
		SubNode = "O23",
		Text = "Perhaps I can explain items for you?",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	O23 = {
		Type = 3,
		SubNode = "T25",
		NextNode = "L65",
		Text = "Yes",
		HasCondition = false,
		HasResolver = false,
	},
	T25 = {
		Type = 2,
		SubNode = "T26",
		Text = "There are many items to assist you on the battlefield. Just be weary of your \nstock as you don't want to waste them.",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	T26 = {
		Type = 2,
		SubNode = "T58",
		Text = "For example, a bacta container will heal a portion of \nyour health. It can only be used once.",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	T58 = {
		Type = 2,
		SubNode = "T81",
		Text = "Likewise, the Assault Droid, which has a limited battery life, \nwill be used up when you use it and float around you for a \nperiod of time before it self-destructs.",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	T81 = {
		Type = 2,
		SubNode = "O82",
		Text = "Would you like to know anything more?",
		Duration = 3500,
		HasCondition = false,
		HasResolver = false,
	},
	O82 = {
		Type = 3,
		SubNode = "L85",
		NextNode = "L84",
		Text = "Yes, please.",
		HasCondition = false,
		HasResolver = false,
	},
	L85 = {
		Type = 4,
		Target = "T49",
	},
	L84 = {
		Type = 4,
		NextNode = "L98",
		Target = "O51",
	},
	L98 = {
		Type = 4,
		Target = "O93",
	},
	L65 = {
		Type = 4,
		NextNode = "O24",
		Target = "O51",
	},
	O24 = {
		Type = 3,
		SubNode = "T49",
		NextNode = "L100",
		Text = "No thanks, anything else I should know?",
		HasCondition = false,
		HasResolver = false,
	},
	T49 = {
		Type = 2,
		SubNode = "O50",
		Text = "I can tell you about weapon variations.",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	O50 = {
		Type = 3,
		SubNode = "T86",
		NextNode = "O51",
		Text = "Go ahead.",
		HasCondition = false,
		HasResolver = false,
	},
	T86 = {
		Type = 2,
		SubNode = "T87",
		Text = "Some weapons in the shop will cost more than others. \nOn first glance, they may appear to be the same.",
		Duration = 5200,
		HasCondition = false,
		HasResolver = false,
	},
	T87 = {
		Type = 2,
		SubNode = "T88",
		Text = "However, look closely at their name and you will some weapons have attachments.",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	T88 = {
		Type = 2,
		SubNode = "T89",
		Text = "For example, a scope or a stun attachment is common for blaster rifles.",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	T89 = {
		Type = 2,
		SubNode = "L105",
		Text = "Pick the right kind of attachment for your fighting style and for the battlefield. \nA scoped weapon won't be very useful in cramped spaces!",
		Duration = 5300,
		HasCondition = false,
		HasResolver = false,
	},
	L105 = {
		Type = 4,
		Target = "O51",
	},
	O51 = {
		Type = 3,
		SubNode = "T63",
		NextNode = "L97",
		Text = "Can I ask you some other questions?",
		HasCondition = false,
		HasResolver = false,
	},
	T63 = {
		Type = 2,
		SubNode = "O64",
		Text = "Certainly!",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	O64 = {
		Type = 3,
		SubNode = "L66",
		NextNode = "O69",
		Text = "How do I purchase a weapon?",
		HasCondition = false,
		HasResolver = false,
	},
	L66 = {
		Type = 4,
		Target = "T10",
	},
	O69 = {
		Type = 3,
		SubNode = "L70",
		NextNode = "O67",
		Text = "What's my objective?",
		HasCondition = false,
		HasResolver = false,
	},
	L70 = {
		Type = 4,
		Target = "T5",
	},
	O67 = {
		Type = 3,
		SubNode = "L68",
		NextNode = "O71",
		Text = "Do you have any tips for me?",
		HasCondition = false,
		HasResolver = false,
	},
	L68 = {
		Type = 4,
		Target = "T40",
	},
	O71 = {
		Type = 3,
		SubNode = "L77",
		NextNode = "O73",
		Text = "Anything I should know before I purchase weapons?",
		HasCondition = false,
		HasResolver = false,
	},
	L77 = {
		Type = 4,
		Target = "T18",
	},
	O73 = {
		Type = 3,
		SubNode = "L103",
		Text = "Actually, I'll be going now.",
		HasCondition = false,
		HasResolver = false,
	},
	L103 = {
		Type = 4,
		Target = "T94",
	},
	L97 = {
		Type = 4,
		Target = "O93",
	},
	L100 = {
		Type = 4,
		Target = "O93",
	},
	O21 = {
		Type = 3,
		SubNode = "T28",
		NextNode = "L99",
		Text = "That would help a lot!",
		HasCondition = false,
		HasResolver = false,
	},
	T28 = {
		Type = 2,
		SubNode = "T29",
		Text = "Their are a few different types of weapons\nyou will find available to you.",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	T29 = {
		Type = 2,
		SubNode = "T30",
		Text = "The pistols are cheap, but often have a small clip \nand will require good aiming in order to survive.",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	T30 = {
		Type = 2,
		SubNode = "T31",
		Text = "If you plan on using a pistol to begin with, \nyou should stay with your teammates.\nTry to rely on assistance rewards.",
		Duration = 6000,
		HasCondition = false,
		HasResolver = false,
	},
	T31 = {
		Type = 2,
		SubNode = "T32",
		Text = "Pistols are cheap, so it won't be long \nbefore you can afford a better gun.",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	T32 = {
		Type = 2,
		SubNode = "T33",
		Text = "Slugthrower carbines are a cheap and crude weapon, \nbut they have a high fire rate and good stopping power.",
		Duration = 4000,
		HasCondition = false,
		HasResolver = false,
	},
	T33 = {
		Type = 2,
		SubNode = "T34",
		Text = "They cost more than a pistol, but you will most likely \ntake down more targets with a slugthrower carbine \nso you can recoup your credits quickly.",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	T34 = {
		Type = 2,
		SubNode = "O59",
		Text = "Is there anything else I can help you with?",
		Duration = 4500,
		HasCondition = false,
		HasResolver = false,
	},
	O59 = {
		Type = 3,
		SubNode = "L60",
		NextNode = "L62",
		Text = "Yes, please.",
		HasCondition = false,
		HasResolver = false,
	},
	L60 = {
		Type = 4,
		Target = "T22",
	},
	L62 = {
		Type = 4,
		NextNode = "L96",
		Target = "O51",
	},
	L96 = {
		Type = 4,
		Target = "O93",
	},
	L99 = {
		Type = 4,
		Target = "O93",
	},
	O38 = {
		Type = 3,
		SubNode = "T40",
		NextNode = "O93",
		Text = "Do you have any tips for me?",
		HasCondition = false,
		HasResolver = false,
	},
	T40 = {
		Type = 2,
		SubNode = "T41",
		Text = "Certainly!",
		Duration = 1000,
		HasCondition = false,
		HasResolver = false,
	},
	T41 = {
		Type = 2,
		SubNode = "T42",
		Text = "It is worth learning to use the sights on your gun. \n",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	T42 = {
		Type = 2,
		SubNode = "T43",
		Text = "Also, try not to run while firing unless \nyou really need to make a fast escape.",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	T43 = {
		Type = 2,
		SubNode = "T44",
		Text = "Lastly, try to stay with your teammates, and \ndon't run along side them. ",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	T44 = {
		Type = 2,
		SubNode = "T45",
		Text = "Not only can it become hard to get to cover when \nyou're tripping over your teammates, but the \nenemy may have placed mines nearby.",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	T45 = {
		Type = 2,
		SubNode = "T46",
		Text = "Staying a good five paces away from your teammate minimizes\nthe chances that a mine should kill you both! ",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	T46 = {
		Type = 2,
		SubNode = "L76",
		Text = "Is there anything else you would like to know?",
		Duration = 5000,
		HasCondition = false,
		HasResolver = false,
	},
	L76 = {
		Type = 4,
		NextNode = "L95",
		Target = "O51",
	},
	L95 = {
		Type = 4,
		Target = "O93",
	},
	O93 = {
		Type = 3,
		SubNode = "T94",
		Text = "No, I'm alright. Good-bye.",
		HasCondition = false,
		HasResolver = false,
	},
	T94 = {
		Type = 2,
		SubNode = "D104",
		Text = "You can talk to me at a later time. ",
		Duration = 3000,
		HasCondition = false,
		HasResolver = false,
	},
	D104 = {
		Type = 5,
	},
}
