version: 1.0.{build}

branches:
  only:
  - master
  - develop
  
os: Visual Studio 2015

configuration: Release

install:
- cmd: >-
    if not exist build mkdir build
    
    cd build
    
    cmake -G "Visual Studio 14" -T v140_xp -DCMAKE_INSTALL_PREFIX=DESTDIR ..
    
build_script:
- cmd: cmake --build . --target ALL_BUILD --config Release

after_build:
  - cmd: cmake --build . --target INSTALL --config Release
  - cmd: 7z a jkgalaxies-win32.zip DESTDIR/JediAcademy/*.exe DESTDIR/JediAcademy/JKG/*.dll DESTDIR/JediAcademy/*.dll
    
artifacts:
 - path: build/jkgalaxies-win32.zip
